RedRoverSchool/LumaProjectPython_2024_spring

pages/locators.py, tests/test_sale_women_sale.py
=> TC_011.011.001 | Sale > Breadcrumbs are visible and correct on women sale page

data/links.py, locators/woman_page_locators.py, pages/woman_page.py, tests/test_woman_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;1kNep1VB">TC_007.001.001 | Women &gt;Dropdown menu&gt;Checking page redirection to Tops elements</a>
=> TC_007.001.001 | Women >Dropdown menu>Checking page redirection to Tops elements

tests/test_sale_page.py
=> TC_011.004.04 | Sale > GEAR DEALS on side panel > Visibility of name GEAR DEALS

tests/test_redirect_after_add_product_to_wishlist.py
https://trello.com/c/jgLmzBZX/296-tc006004005-whats-new-eco-collection-new
=> Create product to wish-list as non logged in user

tests/test_search_terms.py
=> TC_015.001.001 | Popular Search Terms > Title is visible

data/links.py, locators/woman_page_locators.py, pages/locators.py, pages/woman_page.py, tests/test_woman_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nHfwIzLO">TC_007.001.002 | Women &gt;Dropdown menu&gt; Checking page redirection to Bottom elements</a></blockquote>
=> TC_007.001.002 | Women >Dropdown menu> Checking page redirection to Bottom elements

tests/test_search_terms.py
=> TC_015.001.002 | Popular Search Terms > Number of search terms is 100

.github/workflows/ci.yml, pages/forgot_password.py, tests/test_reset_password.py
=> TC_004.003.001 | Sign in>Registration, Account >Sign in>Check reset user password

tests/test_women_tee.py
=> TC_011.016.001 | Sale > Tees-women > Breadcrumbs are visible and correct

tests/test_sale_page.py
=> TC_011.004.06 | Sale > GEAR DEALS on side panel > Visibility of link Fitness Equipment

tests/test_sale_page.py
=> TC_011.004.01 | Sale > GEAR DEALS on side panel > Check Bags link clickability

tests/test_sale_page.py
=> TC_011.004.02 | Sale > GEAR DEALS on side panel > Check Fitness Equipment link clickability

tests/test_sale_page.py
=> TC_011.004.03 | Sale > GEAR DEALS on side panel > Check Bags link correct redirection

tests/test_sale_page.py
=> TC_011.004.07 | Sale > GEAR DEALS on side panel > Check Fitness Equipment link correct redirection

data/links.py, data/page_data.py, pages/locators.py, pages/main_page.py, tests/test_footer_privacy_and_cookie_policy.py
https://trello.com/c/MGEOisOH/308-tc012006001-footer-privacy-and-cookie-policy-redirect-clickability-visability-verify-visibility-of-the-privacy-and-cookie-policy
=> TC_012.006.001 | Footer > Privacy and Cookie Policy > Verify visibility of the 'Privacy and Cookie Policy' link

tests/test_sale_page.py
=> link_correct_redirection_bag

requirements.txt, tests/test_redirect_to_contact_form_from_private_policy.py
[https://trello.com/c/JMia3A7B/120-tc020002001-privacy-and-cookie-policycontact-us-link-verify-redirect-from-policy-page-to-contact-form](https://github.com/RedRoverSchool/LumaProjectPython_2024_spring/pull/16)
=> Tc 020.002.001|Privacy and Cookie Policy>Contact us link> Verify redirect from Policy page to Contact form

pages/locators.py, pages/main_page.py, tests/test_whats_new.py
https://trello.com/c/VNhzWWei/95-tc006006001-whats-new-page-check-whats-new-link-visibility
=> TC_006.006.001 | What's new page > Check What's New link visibility

pages/empty_cart_icon_page.py, tests/test_the_empty_cart_icon.py
https://trello.com/c/L5CT9TYK/154-tc003003001-header-cartverify-the-cart-icon-is-visible-and-clickable-on-main-page
=> TC_003.003.001| Header > Cart>Verify the cart icon is visible and clickable on main page

data/links.py, pages/locators.py, pages/main_page.py, pages/whats_new_page.py, tests/test_whats_new.py
https://trello.com/c/wRvM6M3F/96-tc006006002-whats-new-page-check-redirection-to-whats-new-page-by-clicking-a-link
=> TC_006.006.002 | What's new page > Check redirection to What's New page by clicking a link

luma.dockerfile, pages/my_account.py, pages/sign_in.py, tests/test_sign_in.py
=> TC_004.005.004 | Sign in & Registration, Account >Sign in_(authorization) > Login with good credentials

pages/main_page.py
https://trello.com/c/n3r3I5C7/339-rf012006001-mainpagepy-scrolltoprivacycookiepolicylink-footer-privacy-and-cookie-policy-redirect-clickability-visibility
=> RF_012.006.001 | main_page.py > scroll_to_privacy_cookie_policy_link > Footer > Privacy and Cookie Policy > Redirect, Clickability, Visibility

pages/privacy_block_page.py, tests/test_all_links_in_privacy_block_are_visible.py
https://trello.com/c/sRAofRDe/186-tc020001001-privacy-and-cookie-policy-main-content-all-links-in-the-block-on-the-left-are-visible
=> TC_020.001.001 | Privacy and Cookie Policy >Main Content> All links in the block on the left are visible

pages/locators.py, pages/main_page.py, tests/test_verifying_men_link_is_displayed_clickable_redirection.py
=> Verifying Men > Displayed, Clickable, Redirection from Main page

tests/test_sale_women_sale.py, tests/test_sign_in.py
=> TC_004.005.005 | Sign in & Registration, Account >Sign in_(authorization) > Sign-in error handling & redirection

tests/test_women_tee.py
=> TC_011.016.002 | Sale > Tees-women > Breadcrumbs redirects to the correct pages

tests/test_women_page.py, tests/test_women_tee.py
=> TC_011.011.002 | Sale > Women's Deals > Breadcrumbs redirects to the correct page

pages/locators.py, tests/test_sign_in.py, tests/test_women_tee.py
=> TC_004.005.001 | Sign in & Registration, Account >Sign in_(authorization) > Login without password

tests/test_sign_in.py
=> TC_004.005.002 | Sign in & Registration, Account >Sign in_(authorization) > Successful login

pages/locators.py, tests/test_footer_links_presence.py
[Verify the footer of every page on the website contains the list of links](https://trello.com/c/PMzBgZUn)
=> TC_012.001.001 I Footer > Visibility, Clickability, Redirect > Verify the footer of every page on the website contains the list of links

pages/redirect_inside_cart_LK.py, tests/test_redirect_inside_cart_LK.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BCAxPhUO">TC_005.001.002| Main page &gt; Cart&gt; User redirected inside the cart</a></blockquote>
=> TC_005.001.002| Main page > Cart> User redirected inside the cart

conftest.py, pages/whats_new_page.py, pages/wish_list.py, tests/test_wish_list.py
=> TC_014.001.004 | Wish list > Visibility, Clickability > Check button "Update Wish List" is clickable

pages/locators.py, tests/test_all_links_are_highlited.py, tests/test_footer_links_presence.py, tests/test_sign_in.py, tests/test_women_page.py
=> TC_004.005.003 | Sign in & Registration, Account >Sign in_(authorization) > After successful login user sees his nickname on each page

pages/locators.py, pages/main_page.py, tests/test_men_page.py
[Verify redirection option "Men" menu item to the corresponding page from the "Home Page"](https://trello.com/c/4WFy9z5C)
=> TC_008.001.005 I Men > Displayed, Clickability, Redirection > Verify redirection option "Men" menu item to the corresponding page from the "Home Page"

data/links.py, pages/sale_page.py, tests/test_sale_page.py
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pyqtpSob">TC_011.007.002 | Sale &gt; Block “Women’s Deals” &gt; Verify clickability of a button &quot;Shop Women&#39;s Deals&quot;</a></blockquote>
=> TC_011.007.002 | Sale > Block “Women’s Deals” > Verify clickability of a button "Shop Women's Deals"

data/page_data.py, pages/locators.py, pages/main_page.py, tests/test_footer_privacy_and_cookie_policy.py, tests/test_main_page_new_luma_yoga_collection_block.py
https://trello.com/c/rKXY69Mo/364-tc001005001-main-page-new-luma-yoga-collection-view-the-new-luma-yoga-collection-block-verify-displays-of-the-new-luma-yoga-coll
=> TC_001.005.001 Main Page > New Luma Yoga Collection  > Verify displays of the 'New Luma Yoga Collection' block

data/page_data.py, pages/copyright_info.py, tests/test_copyright_information_visibility.py
https://trello.com/c/AmBznN3p/160-tc012002001-footer-copyright-information-visibility
=> TC_012.002.001 | Footer > Copyright information visibility

tests/test_search_terms.py
=> TC_015.001.003 | Popular Search Terms > Search terms in the list have sizes, ranging from 76% to 136%

data/links.py, pages/components/nav_wigdet.py, pages/locators.py, pages/men_page.py, tests/test_verifying_men_link_is_displayed_clickable_redirection.py
=> Men's Clothing Section Display, Clickable, and Redirection step(7-11)

pages/locators.py, pages/whats_new_page.py, tests/test_whats_new.py
https://trello.com/c/bCZOe2Tp/97-tc006006003-whats-new-page-check-lumas-latest-list-visibility
=> TC_006.006.003 | What's new page > Check Luma`s latest list visibility

conftest.py, pages/wish_list.py, tests/test_wish_list.py
=> TC_014.003.002 | Wish list > Removing items

pages/whats_new_page.py, pages/wish_list.py, tests/test_redirect_after_add_product_to_wishlist.py, tests/test_remove_and_edit_items_from_wish_list.py
https://trello.com/c/zbRUOa7r
Wish list > Removing and Edit Items
=> TC_014.003.003| Wish list > Removing and Edit Items

conftest.py, pages/locators.py, pages/training_page.py, tests/test_training_page.py, tests/test_women_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sQZTeeBf">TC_010.003.001 | Training &gt; Category &quot;Video Download&quot; &gt; Verify clickability and visibility of the &#39;Video Download&#39; link</a></blockquote>
=> TC_010.003.001 | Training > Category Video Download > Verify clickability and visibility of the Video Download link

pages/search_terms_page.py, tests/test_search_terms.py
=> TC_015.002.006 Popular Search Terms > Visibility and clickability> Verify the order of popular search terms

pages/locators.py, pages/women_page.py, tests/test_women_tee.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SKLAh5ku">TC_002.001.001 | Radiant Tee product page &gt; Visibility of product name, price and photo</a></blockquote>
=> TC_002.001.001 | Radiant Tee product page > Visibility of product name, price and photo

pages/erin_recommends_page.py, pages/locators.py, tests/test_erin_recoomends.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Xwdzlpus">TC_001.002.004 | Main Page &gt; Erin Recommendations &gt; Select Number of Products Displayed</a></blockquote>
=> TC_001.002.004 | Main Page > Erin Recommendations > Select Number of Products Displayed

data/links.py, pages/locators.py, pages/whats_new_page.py, tests/test_yoga.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jqrXmRkR">TC_006.007.002| What`s new page &gt; New Luma Yoga Collection &gt; The &quot;New Luma Yoga Collection&quot; link redirects to New Luma Yoga Collection page</a></blockquote>
=> TC_006.007.002| What`s new page > New Luma Yoga Collection > The "New Luma Yoga Collection" link redirects to New Luma Yoga Collection page

pages/locators.py, tests/test_search_terms.py, tests/test_women_tee.py
=> TC_015.001.006 | Popular Search Terms > List of keywords is sorted alphabetically

tests/test_yoga.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;oTH09O30">TC_006.007.003| What`s new page &gt; New Luma Yoga Collection &gt; The &quot;Shop New Yoga&quot; button link redirects to New Luma Yoga Collection page</a></blockquote>
=> TC_006.007.003| What`s new page > New Luma Yoga Collection > The "Shop New Yoga" button link redirects to New Luma Yoga Collection page

data/links.py, data/page_data.py, pages/locators.py, pages/men_sale_page.py, tests/test_men_sale_page.py
https://trello.com/c/j98xpncK/402-tc011012001-sale-mens-deals-verify-bread-crumbs-display
=> TC_011.012.001 | Sale > Men’s Deals > Verify Bread Crumbs display

data/links.py, pages/locators.py, pages/yoga_page.py, tests/test_yoga.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jRy1WrCH">TC_006.007.004| What`s new page &gt; New Luma Yoga Collection &gt; The &quot;List&quot; button is displayed and changes a page view type</a></blockquote>
=> TC_006.007.004| What`s new page > New Luma Yoga Collection > The "List" button is displayed and changes a page view type

pages/locators.py, pages/yoga_page.py, tests/test_yoga.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;k2lE2NmK">TC_006.007.005| What`s new page &gt; New Luma Yoga Collection &gt; The &quot;Grid&quot; button is displayed and changes a page view type</a></blockquote>
=> TC_006.007.005| What`s new page > New Luma Yoga Collection > The "Grid" button is displayed and changes a page view type

pages/base_page.py, pages/locators.py, pages/training_page.py, tests/test_training_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;UBj6f2Xa">TC_010.003.002 | Training &gt; Category &quot;Video Download&quot; &gt; Check the redirection to the &quot;Video Download&quot; page.</a></blockquote>
=> TC_010.003.002 | Training>Category Video Download>Check the redirection to the Video Download page.

tests/test_search_terms.py
=> TC_015.002.005 Popular Search Terms > Visibility and clickability> Verify the absence of duplicate keywords

pages/performans_new_page.py, pages/user.py, tests/test_performance_sportswear_new.py
=> TC_006.008.06 | What's new > Performance Sportswear New > Check count  of products

data/page_data.py, pages/locators.py, pages/men_sale_page.py, tests/test_men_sale_page.py
=> TC_011.012.002 | Sale > Men’s Deals > Verify page title

pages/base_page.py, pages/locators.py, pages/training_page.py, tests/test_training_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GvCkcdic">TC_010.004.001 | Training &gt; &quot;Block-promo training-main&quot; &gt; Verify visibility &quot;Block 1&quot;</a></blockquote>
=> TC_010.004.001 | Training > "Block-promo training-main" > Verify visibility "Block 1"

tests/test_search_terms.py
=> TC_015.002.003 Popular Search Terms > Visibility and clickability> Verify the absence of duplicate keywords

data/page_data.py, pages/locators.py, pages/training_page.py, tests/test_training_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;V9sTn1i3">TC_010.004.002 | Training &gt; Block 1 ( &quot;Block-promo training-main&quot;) &gt; Verify Block 1 consists text</a></blockquote>
=> TC_010.004.002 | Training > Block 1 ( "Block-promo training-main") > Verify Block 1 consists text

pages/locators.py, pages/men_sale_page.py, tests/test_men_sale_page.py
=> TC_011.012.003 | Sale > Men’s Deals > Verify total number of items on the page

data/links.py, data/page_data.py, pages/locators.py, pages/set_of_sprite_yoga_straps_page.py, tests/test_fitness_equipment.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sLFXvIMH">TC_009.005.003| Gear catalog &gt; Fitness Equipment &gt; Set of Sprite Yoga Straps &gt; Adding more than the available quantity &quot;Sprite Yoga Strap 6 foot&quot; to Shopping Cart</a></blockquote>
=> TC_009.005.003|Gear catalog>Fitness Equipment>Adding more than the available quantity "Sprite Yoga Strap 6 foot" to Shopping Cart

conftest.py, data/links.py, data/page_data.py, pages/locators.py, tests/test_check_quantity_items_are_displayed_in_compare_products_section.py
https://trello.com/c/j1Blqp6c/371-tc011005003-sale-compare-products-on-side-panelverify-the-compare-products-link-will-display-quantity-of-selected-products
=> TC_011.005.003 | Sale > Compare Products on side panel>Verify the Compare products link will display Quantity of selected products

pages/base_page.py, pages/cart_page.py, pages/components/mini_card.py, pages/components/nav_wigdet.py, pages/erin_recommends_page.py, pages/locators.py, pages/main_page.py, pages/men_sale_page.py, pages/whats_new_page.py, pages/wish_list.py, tests/test_cart.py, tests/test_erin_recoomends.py, tests/test_minicart.py, tests/test_purchase_products_with_discount.py, tests/test_redirect_after_add_product_to_wishlist.py, tests/test_remove_and_edit_items_from_wish_list.py, tests/test_whats_new.py, tests/test_yoga.py
[create test purchase products](https://trello.com/c/9c2BadPx)
=> Sale > 20% OFF: Purchase of goods with a 20% discount

pages/locators.py, pages/training_page.py, tests/test_training_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EUB3f5Ma">TC_010.004.003 | Training &gt; Block 1 ( &quot;Block-promo training-main&quot;) &gt; Verify Block 1 dimensions</a></blockquote>
=> TC_010.004.003 | Training > Block 1 ( "Block-promo training-main") > Verify Block 1 dimensions

pages/locators.py, pages/main_page.py, pages/product_page.py, pages/women_page.py, tests/test_whats_new.py, tests/test_women_tee.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xGtHnQaq">TC_002.001.002 | Radiant Tee product page &gt; Add to cart &gt; Adding the product to cart</a></blockquote>
+ changes to starting to fail TC_002.001.001
=> TC_002.001.002 | Radiant Tee product page > Add to cart > Adding the product to cart

data/links.py, data/page_data.py, pages/base_page.py, pages/locators.py, pages/popular_search_terms_page.py, tests/test_popular_search_terms.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YgMgvvIu">TC_015.003.002 | Popular Search Terms &gt; Redirection &gt; The page title contains &quot;Search results for:&quot; and the keyword</a></blockquote>
=> TC_015.003.002_Popular Search Terms > Redirection > The page title contains "Search results for:" and the keyword

tests/test_check_quantity_items_are_displayed_in_compare_products_section.py, tests/test_men_sale_page.py, tests/test_remove_and_edit_items_from_wish_list.py, tests/test_search_terms.py, tests/test_wish_list.py, tests/test_women_tee.py, tests/test_yoga.py
=> TC_015.001.005 | Popular Search Terms > Keywords HOODIE, jacket, pants, shirt have enlarged font size

conftest.py, data/links.py, pages/locators.py, tests/test_performance_sportswear_new.py
=> TC_006.008.001 | What's new > Performance Sportswear New > Visibility of Product name, its Price and Photo

data/links.py, pages/locators.py, tests/test_performance_sportswear_new.py
https://trello.com/c/cmwZ3A6P
https://trello.com/c/WjUokO7r
https://trello.com/c/dYQgmbfJ
=> TC_006.008.002 | What's new > Performance Sportswear New > 3 tests

pages/locators.py, pages/whats_new_page.py, tests/test_whats_new.py
=> TC_006.005.001 | Verify that User gets error message This this is required field in red color

tests/test_search_terms.py
=> TC_015.001.004 | Popular Search Terms > At least 5 search terms in the list have font size larger than 88%

data/links.py, pages/locators.py, pages/whats_new_page.py, tests/test_whats_new.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aj3EgeOa">TC_006.002.003 I What&#39;s new &gt; Eco Collection New* &gt; Redirection to the product page by clicking on the image</a></blockquote>
=> TC_006.002.003 I What's new > Eco Collection New* > Redirection to the product page by clicking on the image

pages/base_page.py, pages/create_account.py, pages/gear_page.py, tests/test_link_create_an_account.py
Please check my new PR. Thank you!
=> TC_004.004.006 | Sign in & Registration, Account >Create an Account > Visibility and Functionality of "Create an account" Link

pages/erin_recommends_page.py, pages/locators.py, tests/test_erin_recoomends.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SiNG1wlV">TC_001.002.005 | Main Page &gt; Erin Recommendations &gt; Arrangement of Products Display</a></blockquote>
=> TC_001.002.005 | Main Page > Erin Recommendations > Arrangement of Products Display

pages/performans_new_page.py, pages/user.py, tests/test_performance_sportswear_new.py
=> TC_006.008.06 | What's new > Performance Sportswear New > Check count of products

pages/base_page.py, pages/locators.py, pages/training_page.py, tests/test_training_page.py, tests/test_women_tee.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JgK1dTWX">TC_010.004.004 | Training &gt; Block 1 ( &quot;Block-promo training-main&quot;) &gt; Verify the picture format</a></blockquote>
=> TC_010.004.004 | Training > Block 1 ( "Block-promo training-main") > Verify the picture format

data/links.py, pages/locators.py, tests/test_basket_without_login.py
=> TC_004.001.002 | Sign in & Registration, Account > Anonym User > Checkout from mini-cart

pages/erin_recommends_page.py, pages/locators.py, tests/test_erin_recoomends.py
=> TC_001.002.015_1 | Main Page > Erin Recommendations > Adding an Item for Comparison

data/links.py, tests/test_sale_page.py
[Sale > Verify redirection to the sale page from any page](https://trello.com/c/4slhRo2E)
=> TC_011.001.004 | Sale > Verify redirection to the sale page from any page

pages/locators.py, pages/tees_page.py, tests/test_check_four_similar_tees_discount_is_applied.py
https://trello.com/c/pe2cXboc/452-tc011016-sale-tees-women-check-discount-4-tees-for-the-price-of-3-is-applied-for
=> TC_011.016 | Sale > Tees-women->Check discount 4 tees for the price of 3 is applied for similar Tees

data/links.py, pages/compare_side_panel.py, pages/locators.py, pages/sale_page.py, tests/test_sale_page.py, tests/test_sign_in.py
=> TC_011.005.003 | Sale > Compare Products on side panel >Verify all selected items are displayed in the section "Compare products”

tests/test_presence_of_contact_us_link.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0rFrHBHE">TC_020.002.003 | Privacy and Cookie Policy &gt; Contact us link &gt; Verify the presence of the &quot;Contact Us&quot; link.</a></blockquote><script src="https://p.trellocdn.com/embed.min.js"></script>
=> TC_020.002.003 | Privacy and Cookie Policy > Contact us link > Verify the presence of the "Contact Us" link.

pages/locators.py, pages/women_page.py, tests/test_copyright_information_visibility.py, tests/test_footer_links_presence.py, tests/test_women_sale.py
=> TC_012.003_002 | Footer > "Search terms" link > Correct redirection for unauthorized user

pages/locators.py, pages/sale_page.py, tests/test_sale_page.py
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mZOkRDzP">TC_011.008.001 | Sale &gt; Block “Men’s Deals”&gt;Visibility of image and text</a>
=> TC_011.008.001 | Sale > Block “Men’s Deals”>Visibility of image and text

tests/test_contact_us_link_redirects_to_contact_us_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9qBktOT6">US_020.002.004| Privacy and Cookie Policy &gt; Contact us link &gt; Confirmation of the &quot;Contact Us&quot; Link Redirection Functionality.</a></blockquote><script src="https://p.trellocdn.com/embed.min.js"></script>
=> US_020.002.004| Privacy and Cookie Policy > Contact us link > Confirmation of the "Contact Us" Link Redirection Functionality.

pages/gear_page.py, pages/locators.py, pages/performans_new_page.py, pages/set_of_sprite_yoga_straps_page.py, tests/test_fitness_equipment.py, tests/test_performance_sportswear_new.py
=> TC_009.005.004 | Gear catalog > Fitness Equipment > Set of Sprite Yoga Straps > Put set or a few sets of “Sprite Yoga Strap 8 foot” in the cart

pages/locators.py, pages/sale_page.py, pages/whats_new_page.py, tests/test_sale_page.py, tests/test_whats_new.py
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lbjGjlg5">TC_006.002.001| What&#39;s new &gt; Eco Collection New* &gt; Changing the color in product list</a>
=> TC_006.002.001| What's new > Eco Collection New* > Changing the color in product list

data/page_data.py, tests/test_men_sale_page.py
https://trello.com/c/j98xpncK
Fixed changes in excpected result according to TC and US's acceptance criteria
=> RF_011.012.001 | Sale > Men’s Deals > Verify Bread Crumbs display

pages/locators.py, pages/set_of_sprite_yoga_straps_page.py, tests/test_fitness_equipment.py
https://trello.com/c/V6O1wFcf
https://trello.com/c/icLePPJ7
=> TC_009.005.006 | Gear catalog > Fitness Equipment > Set of Sprite Yoga Straps > two tests

data/page_data.py, pages/locators.py, pages/men_sale_page.py, tests/test_men_sale_page.py
=> TC_011.012.005 | Sale > Men’s Deals > Check card arrangement according to chosen option

pages/locators.py, pages/product_page.py, tests/test_women_tee.py
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5xoWR2Ef">TC_002.001.007 | Radiant Tee product page &gt; Product parameters &gt; Changing the product size</a>
=> TC_002.001.007 | Radiant Tee product page > Product parameters > Changing the product size

tests/test_whats_new.py
=> TC_006.005.002 | What's new > Eco Collection New*> Verify User gets error message

pages/base_page.py, pages/locators.py, pages/product_page.py, tests/test_women_tee.py
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IR9y4zwY">TC_002.001.009 | Radiant Tee product page &gt; Adding the product to the wish list</a>
=> TC_002.001.009 | Radiant Tee product page > Adding the product to the wish list

pages/erin_recommends_page.py, tests/test_check_discount_for_four_different_tees_is_applied.py, tests/test_erin_recoomends.py
refactoring to new requirements
=> refactoring to new requirements

pages/training_page.py, tests/test_training_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fkmwz6Ok">RF_010.003 | Training &gt; Category &quot;Video Download&quot; &gt; Visibility, clickability, redirection</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TbvtUfVi">RF_010.004 | Training &gt; Block 1 ( &quot;Block-promo training-main&quot;) &gt; Visibility</a></blockquote>
=> RF | Refactor to new requirements(Training Page)

pages/search_terms_page.py, pages/women_page.py
=> RF tests on Search terms page and Women page

pages/advanced_search.py, pages/locators.py, tests/test_advanced_search.py
TC_016.001.005 | Advanced Search > Entering an incorrect price range
=> def test_incorrect_price_range

pages/sale_page.py, tests/test_sale_page.py
RF TC_011.010.001
https://trello.com/c/O0iYXhy1
=> RF TC_011.010.001 | Verify each image includes a short description of the promotion

pages/advanced_search.py, tests/test_advanced_search.py
added test_prohibited_characters_in_price
=> TC_016.001.003 | Advanced Search > Entering prohibited characters in the “Price from” and “Price to” fields

pages/limiter_item.py, tests/test_show_on_page.py
=> TC_014.002.001 | Wish list > Check Toolbar >Verify filter “Show on page”

pages/wish_list.py, tests/test_wish_list.py
=> TC_011.006.002 | Sale > My Wish List on side panel > Information about items is visible and correct

pages/search_terms_page.py, tests/test_search_terms.py
=> RF_TC_015.002.005 Popular Search Terms > Visibility and clickability> Verify the absence of duplicate keywords

pages/women_page.py, tests/test_women_page.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5dx52ToC">RF_007.001 | Women &gt; Displayed, Clickability, Redirection</a></blockquote>
=> RF| Tests and pages to new requirements and To merge the two test cases into one while

pages/advanced_search.py
locators have been moved to the advanced_search page file;
removed aliases during import.
=> RF | advanced_search tests to the new requirements

pages/limiter_item.py, tests/test_limiter_wish_list.py, tests/test_pagination_wish_list.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4pi1wsxr">TC_014.002.003 | Wish list &gt; Check Toolbar &gt;Verify the function of pagination and display of total number of items on the page</a></blockquote>
=> TC_014.002.003 | Wish list > Check Toolbar >Verify the function of pagination and display of total number of items on the page

pages/search_terms_page.py, tests/test_search_terms.py
=> RF_TC_015.002.003 Popular Search Terms > Visibility and clickability>Verify all links are clickable

pages/advanced_search.py, tests/test_advanced_search.py
https://trello.com/c/fpWChrDR/
=> TC_016.001.008 | Advanced Search > Products found match the search criteria

data/page_data.py, pages/locators.py, tests/test_men_deals.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aUn0RNxA">TC_011.003.001 I Sale &gt; MEN’s DEALS on side panel &gt; Verify &quot;Hoodies and Sweatshirts&quot; link is visible and clickable, correct redirection</a></blockquote>
=> TC_011.003.001 I Sale > MEN’s DEALS on side panel > Verify "Hoodies and Sweatshirts" link is visible and clickable, correct redirection

pages/main_page.py, pages/whats_new_page.py, tests/test_whats_new.py
- deleted class TestWhatsNew
- deleted allure steps in tests
- added allure links to corresponding trello cards
- changed method names according to Victor's recommendations
=> RF_006.006.002 | What's new page > Check redirection to What's New page by clicking a link

pages/advanced_search.py, tests/test_advanced_search.py
=> TC_016.001.004 | Advanced Search > Advanced search is carried out in all fields

pages/product.py, pages/whats_new.py, pages/wish_list.py, tests/test_redirect_after_add_product_to_wishlist.py, tests/test_remove_and_edit_items_from_wish_list.py, tests/test_whats_new.py, tests/test_wish_list.py, tests/test_yoga.py
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lbjGjlg5">TC_006.002.001| What&#39;s new &gt; Eco Collection New* &gt; Changing the color in product list</a>
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;E9ZewRUB">TC_006.002.002| What&#39;s new &gt; Eco Collection New* &gt; Visibility of buttons on product card</a>
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aj3EgeOa">TC_006.002.003 I What&#39;s new &gt; Eco Collection New* &gt; Redirection to the product page by clicking on the image</a>
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GO8VRlcn">TC_006.002.004 I What&#39;s new &gt; Eco Collection New* &gt; Redirection to the product page by clicking on the product name</a></blockquote>
=> Refactoring Whats New -> Eco Collection New tests

pages/advanced_search.py, tests/test_advanced_search.py
https://trello.com/c/cfPCcQjS/
+ added test_non_existent_product
+ locators have been adjusted according to requirements
=> TC_016.001.006 | Advanced Search > Search for a non-existent product

pages/sale.py, tests/test_link_create_an_account.py, tests/test_men_deals.py, tests/test_sale.py, tests/test_wish_list.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kH80u6ta">TC_011.008.002 |Sale &gt; Block “Men’s Deals”&gt;Verify clicking to &quot;Men&#39;s Bargains&quot; image redirect to the &quot;Men Sale&quot; page</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mZOkRDzP">TC_011.008.001 | Sale &gt; Block “Men’s Deals”&gt;Visibility of image and text</a></blockquote>
=> Refactoring Mens Deals tests

tests/test_check_quantity_items_are_displayed_in_compare_products_section.py
test_check_compare_product_item_section_is_empty_after_click_on_clear_all_btn
test_check_quantity_value_in_empty_compare_product_section
=> added skip marks

pages/main_page.py, pages/notes.py, tests/test_notes.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;DIZ062AG">TC_012.005.004 | Footer &gt; Notes&gt; Verify the click on the &quot;PRACTICE API TESTING USING MAGENTO 2&quot; link redirects to the corresponding page</a></blockquote>
=> TC_012.005.004 | Footer > Notes> Verify the click on the "PRACTICE API TESTING USING MAGENTO 2" link redirects to the corresponding page

data/links.py, pages/footer.py, pages/locators.py, tests/test_notes_in_footer_is_visible.py
Added tests for Notes visibility clickability and redirection
https://trello.com/c/LjJnpd6J/420-tc012005003-footer-notes-visibility-and-clickability 
https://trello.com/c/jPZfHFpe/485-tc012005005-footer-notes-clickability?filter=member:devil732704
https://trello.com/c/LlzHLtqd/486-tc012005006-footer-notes-redirection
=> TC_012.005.003, 005, 006| | Footer > Notes > Visibility, clickability, redirection

pages/bags.py, pages/cart.py, tests/test_cart.py
=> TC_004.001.004 | Sign in & Registration, Account > Anonym User can change item quantity in the cart

data/page_data.py, pages/men_sale_page.py, pages/tees_page.py, tests/test_men_sale_page.py, tests/test_wish_list.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bDV6XGTp">TC_011.012.006 | Sale &gt; Men’s Deals &gt; Verify sorting product cards by position</a></blockquote> (test_verify_sorting_product_cards_by_position)
=> attempt to fix the test and added  marks skip

pages/product.py, tests/test_check_quantity_items_are_displayed_in_compare_products_section.py, tests/test_women_tee.py
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ik5u2Zsm">TC_002.001.008 | Radiant Tee product page &gt; Product parameters &gt; Changing the product color</a>
=> TC_002.001.008 | Radiant Tee product page > Product parameters > Changing the product color

pages/product.py, tests/test_check_quantity_items_are_displayed_in_compare_products_section.py, tests/test_women_tee.py
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;R6TsIcuW">TC_002.001.006 | Radiant Tee product page &gt; Reviews &gt; Writing the product review</a>
=> TC_002.001.006 | Radiant Tee product page > Reviews > Writing the product review

pages/search_terms_page.py, tests/test_search_terms.py
=> TC_015.002.004 Popular Search Terms > Visibility and clickability> Verify the destination page for each keyword

pages/advanced_search.py, pages/men_sale_page.py
https://trello.com/c/B85RrqMm
Add solution for failed tests (reason was a stale element)
=> RF_011.012.008 | Sale > Men’s Deals > Verify sorting product cards by product name

pages/men_sale_page.py
@allure.link("https://trello.com/c/B85RrqMm")
@allure.title("Verify sorting product cards by product name")
def test_verify_sorting_product_cards_by_name():
=> fix try(TC_011.012.008) Errore-test_verify_sorting_product_cards_by_name

pages/advanced_search.py, pages/breadcrumbs.py, pages/women_page.py, tests/test_advanced_search.py, tests/test_breadcrumbs.py, tests/test_fitness_equipment.py, tests/test_women_sale.py, tests/test_women_tee.py
modified:  
test_women_sale.py
test_women_tee.py
=> RF Locators removed and moved

pages/advanced_search.py, pages/cart.py, pages/main_page.py, tests/test_cart.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uc7L5J7B">RF_005.001.004| Main page &gt; Cart &gt; Checking the quantity is able to change</a></blockquote>
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gNx17MiV">RF_005.001.005 | Main page &gt; Cart &gt; Checking the product is deleted from the cart</a></blockquote>
=> RF_005.001.004 and RF_005.001.005(new requirements)

pages/main_page.py, tests/test_all_links_are_highlited.py, tests/test_all_links_in_privacy_block_are_visible.py, tests/test_fitness_equipment.py, tests/test_footer_links_presence.py, tests/test_footer_privacy_and_cookie_policy.py, tests/test_forgot_password.py, tests/test_header.py, tests/test_limiter_wish_list.py, tests/test_link_create_an_account.py, tests/test_main_page_auth_links.py, tests/test_main_page_new_luma_yoga_collection_block.py, tests/test_men_deals.py, tests/test_men_page.py, tests/test_men_sale_page.py, tests/test_minicart.py, tests/test_notes.py, tests/test_notes_in_footer_is_visible.py
Delete class
tests/test_footer_privacy_and_cookie_policy.py (corrected according to requirements)
=> Added allure marks part 2 

pages/create_account.py, pages/main_page.py, pages/sign_in.py, tests/test_main_page_auth_links.py
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GEQHU5fa">TC_001.001.003 | Main Page &gt; Main Page &gt; Viewing the main page &gt; The “Sign In” and “Create an Account” links are visible and clickable on the main page</a></blockquote>
=> Refactored test code and added new methods TC_001.001.003
